# Generated by Django 3.2.8 on 2021-10-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorCall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Photo URL'),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
