# Generated by Django 3.2.8 on 2021-10-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorCall', '0002_auto_20211024_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Photo URL'),
        ),
    ]
